#!/usr/bin/env perl
use FindBin qw/ $Bin /;
use lib "$Bin/../lib"; # FIXME
use strict;
use warnings;
use Message::Passing;

{
    package # PAUSE hide
        Message::Passing::Script::WebHooks;
    use Moose;

    extends 'Message::Passing';

    has '+output' => (
        traits => ['NoGetopt'],
    );
}

Message::Passing::Script::WebHooks->start( output => 'WebHooks' );

