#!/usr/bin/env perl
use FindBin qw/ $Bin /;
use lib "$Bin/../lib"; # FIXME
use strict;
use warnings;
use Log::Stash;

{
    package # PAUSE hide
        Log::Stash::Script::WebHooks;
    use Moose;

    extends 'Log::Stash';

    has '+output' => (
        traits => ['NoGetopt'],
    );
}

Log::Stash::Script::WebHooks->start( output => 'WebHooks' );

